--TB_USER 테이블
SELECT * FROM TB_USER;
DELETE FROM TB_USER WHERE ID_SEQ = 203;
UPDATE TB_USER SET ID_LAT = 37.485721, ID_LONG = 127.02911111111 WHERE ID='USER01';

SELECT * from TB_USER where ID = 'test3';

INSERT INTO TB_USER (ID_GUBUN, ID, PW, EMAIL, PHONE, TG_YN, USER_YN)
VALUES('USER', 'kh', 'USER01', 'USER01@GMAIL.COM', '010-0000-0000', 'N', 'Y');

INSERT INTO TB_USER (ID_GUBUN, ID, PW, EMAIL, PHONE, TG_YN, USER_YN)
VALUES('USER', 'USER01', 'USER01', 'USER01@GMAIL.COM', '010-0000-0001', 'N', 'Y');

INSERT INTO TB_USER (ID_GUBUN, ID, PW, EMAIL, PHONE, TG_YN, USER_YN)
VALUES('USER', 'USER02', 'USER02', 'USER02@GMAIL.COM', '010-0000-0002', 'N', 'Y');

UPDATE TB_USER SET USER_YN='Y' WHERE ID='kh';

--qna 테이블
SELECT * FROM TB_QNA;

INSERT INTO TB_QNA (Q_GRP_SEQ, Q_PW, Q_STAT, Q_TITLE, Q_CONTENTS, ID, Q_INST_DT)
VALUES(1, 'USER01', 'R', 'TITLE01', 'CONTENTS01', 'USER01', SYSDATE);

INSERT INTO TB_QNA (Q_GRP_SEQ, Q_PW, Q_STAT, Q_TITLE, Q_CONTENTS, ID, Q_INST_DT)
VALUES(2, 'USER02', 'R', 'TITLE02', 'CONTENTS02', 'USER02', SYSDATE);


--offline 테이블
--study 방 개설
INSERT INTO TB_STUDY VALUES(1,'뭐냐구젠장','왤케어려워','202001150900','kh','copy','y',9);
INSERT INTO TB_STUDY VALUES(1,'뭐냐고젠장','왤케어ㅇㄹ려워','202001150910','kh','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'뭐나교젠장','왤케어ㅇㄹㅇㄹ려워','202001150915','kh','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'뭐sirh','왤케어ㅇㄹㅇㄹ려워','202001150917','kh','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'이건 또 뭐야','왤케어ㅇㄹㅇㄹ려워','202001180917','kh','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'잘하자?','왤케어ㅇㄹㅇㄹ려워','202001190917','','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'뭐하냐?','왤케어ㅇㄹㅇㄹ려워','202001200917','kh','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'후후','왤케어ㅇㄹㅇㄹ려워','202001210917','kh','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'뭐하냐?','왤케어ㅇㄹㅇㄹ려워','202001200917','USER01','co2py','y',9);
INSERT INTO TB_STUDY VALUES(1,'후후','왤케어ㅇㄹㅇㄹ려워','202001210917','USER01','co2py','y',9);
--study 참여
INSERT INTO TB_STD_MBR VALUES(21, 'kh');
INSERT INTO TB_STD_MBR VALUES(2, 'kh');
INSERT INTO TB_STD_MBR VALUES(3, 'kh');
INSERT INTO TB_STD_MBR VALUES(78, 'USER01');
INSERT INTO TB_STD_MBR values(78, 'USER02');
INSERT INTO TB_STD_MBR values(21, 'USER01');
INSERT INTO TB_STD_MBR VALUES(24, 'kh');
INSERT INTO tb_std_mbr values(24, 'USER01');
INSERT INTO tb_std_mbr values(25, 'USER01');
INSERT INTO tb_std_mbr values(25, 'kh');
INSERT INTO tb_std_mbr values(25, 'USER02');
INSERT INTO tb_std_mbr values(78, '');
SELECT * FROM TB_STD_MBR WHERE STD_SEQ = 78;
SELECT ID
FROM TB_STD_MBR
WHERE STD_SEQ=78;


DELETE FROM TB_STD_MBR WHERE ID='USER02';
SELECT * FROM TB_STUDY WHERE STD_SEQ IN (SELECT STD_SEQ  FROM TB_STD_MBR WHERE ID='kh') AND SUBSTR(STD_DT,1,8) = #{stdDt};
SELECT * FROM TB_STUDY;
DELETE FROM TB_STUDY WHERE STD_ID='kh';

SELECT * FROM TB_STD_MBR tsm LEFT JOIN TB_STUDY ts ON tsm.STD_SEQ = ts.STD_SEQ; 


SELECT * FROM TB_USER WHERE ID='USER01';
SELECT * FROM TB_USER ;
-- offline 스터디 - 아이디 'kh' 가진 사람이 참가하고 있는 방을 볼 수 있다.	
SELECT *
FROM
(SELECT (ROW_NUMBER() OVER(PARTITION BY SUBSTR(STD_DT,1,8) ORDER BY STD_DT))RN,
		STD_SEQ, ID, STD_ID, STD_DT, STD_TITLE, STD_CONTENTS, STD_STAT, STD_SHOW_YN, STD_MBR_NUM
		FROM TB_STUDY JOIN TB_STD_MBR 
		USING (STD_SEQ)
		WHERE ID = 'USER01' AND SUBSTR(STD_DT,1,6) = '202001'	
)
WHERE RN BETWEEN 1 AND 3
ORDER BY STD_DT;
-- 그 날에 OFFLINE스터디에 참여하고 있는 'KH' 아이디를 가진 사람의 방정보
SELECT STD_SEQ, ID, STD_TITLE, STD_CONTENTS, STD_DT, STD_ID, STD_STAT, STD_SHOW_YN, STD_MBR_NUM
FROM TB_STUDY JOIN TB_STD_MBR USING (STD_SEQ)
WHERE ID = 'kh'
AND SUBSTR(STD_DT, 1, 8) = '20200121';
SELECT * FROM TB_STUDY;
SELECT STD_SEQ, STD_TITLE, STD_CONTENTS, STD_DT, STD_ID, STD_STAT, STD_SHOW_YN, STD_MBR_NUM
FROM TB_STUDY
WHERE STD_SEQ = 24;


-- TB_CHAT 채팅방
SELECT * FROM TB_CHAT;

INSERT INTO TB_CHAT VALUES(1, 'HAPPY', 'USER01', '202001291800', '202001291700', '202001291900','뭐하는 방?','N');
INSERT INTO TB_CHAT VALUES(2, 'SUPER', 'USER01', '202001301800', '202001301700', '202001301900','뭐하는 방?','N');
INSERT INTO TB_CHAT VALUES(3, 'SUPER12', 'USER01', '202001301800', '202001301700', '202001301900','뭐하는 방?','N');
DELETE FROM TB_CHAT WHERE CHAT_TITLE ='SUPER';

SELECT CHAT_TITLE, CHAT_MGR, CHAT_ST_DT, CHAT_NUM
	FROM TB_CHAT
	WHERE CHAT_STAT = 'R'
	ORDER BY CHAT_ST_DT;


--TB_CHAT_MBR
SELECT * FROM TB_CHAT_MBR;
INSERT INTO TB_CHAT_MBR VALUES(1, 'kh', 'www.jwddlv',NULL);
INSERT INTO TB_CHAT_MBR VALUES(4, 'USER02', 'www.jwddlv',NULL);
INSERT INTO TB_CHAT_MBR VALUES(4, 'kh', 'www.jwddlv',NULL);
INSERT INTO TB_CHAT_MBR VALUES(5, 'kh', 'www.jwDFddlv',NULL);
DELETE FROM TB_CHAT_MBR WHERE ID='USER02';

INSERT INTO TB_CHAT_MBR VALUES(
(SELECT CHAT_SEQ FROM TB_CHAT WHERE CHAT_MGR='kh' 
AND CHAT_ST_DT='202001090500'),'kh',NULL,NULL);
-- 개설된 online에 참여하고 있는 사람의 해당 달의 방정보들...
SELECT *
FROM
(SELECT (ROW_NUMBER() OVER(PARTITION BY SUBSTR(CHAT_ST_DT,1,8) ORDER BY CHAT_ST_DT))RN, CHAT_SEQ, CHAT_TITLE, 
CHAT_MGR, CHAT_ST_DT,  CHAT_STAT, CHAT_TG_YN, ID, CM_DOC, CM_CHAT_NO
FROM TB_CHAT JOIN TB_CHAT_MBR 
USING (CHAT_SEQ)
WHERE ID = 'kh' AND SUBSTR(CHAT_ST_DT,1,6) = '202001')
WHERE RN BETWEEN 1 AND 3
ORDER BY CHAT_ST_DT
