--초기화 해야해서.... drop먼저 아래에서 위로 한번, 위에서 아래로 한번 하시고  순서대로 추가해주세요
-- 변경사항 -- 등록을 하는 날짜(qna)를 제외하고 날짜를 다루는 컬럼의 값을 VARCHAR2로 변환했음.
-- 이때 DATE를 YYYYMMDDHHmm으로 처리해서 12자리로 통일.

--채팅테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_CHAT_AI_TRG;
DROP SEQUENCE TB_CHAT_SEQ;
DROP TABLE TB_CHAT;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_CHAT
(
    CHAT_SEQ         NUMBER          NOT NULL, 
    CHAT_TITLE       VARCHAR2(20)    NOT NULL, 
    CHAT_MGR         VARCHAR2(20)    NOT NULL, 
    CHAT_ST_DT       VARCHAR2(12)    NOT NULL, 
    CHAT_END_DT      VARCHAR2(12)    NOT NULL, 
    CHAT_FINAL_DT    VARCHAR2(12)    NOT NULL, 
    CHAT_STAT        VARCHAR2(20)    NOT NULL    
    CONSTRAINT TB_CHAT_PK PRIMARY KEY (CHAT_SEQ)
);
ALTER TABLE TB_CHAT ADD CHAT_NUM NUMBER;
ALTER TABLE TB_CHAT DROP COLUMN CHAT_END_DT;
ALTER TABLE TB_CHAT DROP COLUMN CHAT_FINAL_DT;
ALTER TABLE TB_CHAT DROP COLUMN CHAT_TG_YN;

CREATE SEQUENCE TB_CHAT_SEQ;

CREATE OR REPLACE TRIGGER TB_CHAT_AI_TRG
BEFORE INSERT ON TB_CHAT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_CHAT_SEQ.NEXTVAL
    INTO :NEW.CHAT_SEQ
    FROM DUAL;
END;

--유저테이블
--DROP 트리거, 시퀀스, 테이블
DROP SEQUENCE TB_USER_SEQ;
DROP TABLE TB_USER;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_USER
(
    ID_GUBUN    VARCHAR2(20)    NOT NULL, 
    ID_SEQ      NUMBER          NOT NULL, 
    ID          VARCHAR2(20)    NOT NULL, 
    PW          VARCHAR2(20)    NOT NULL, 
    EMAIL       VARCHAR2(50)    NOT NULL, 
    PHONE       VARCHAR2(50)    NOT NULL, 
    TG_NO       VARCHAR2(20)    NULL, 
    TG_YN       CHAR(1)         NOT NULL, 
    USER_YN     CHAR(1)         NOT NULL, 
    AP_RSLT     VARCHAR2(20)    NULL, 
    OUT_RS      VARCHAR2(20)    NULL, 
    DAL_CNT     NUMBER          NULL, 
    CONSTRAINT TB_USER_PK PRIMARY KEY (ID)
);

ALTER TABLE TB_USER ADD ID_LAT NUMBER DEFAULT 0;
ALTER TABLE TB_USER ADD ID_LONG NUMBER DEFAULT 0;

CREATE SEQUENCE TB_USER_SEQ
START WITH 1
INCREMENT BY 1;

--채팅 참여 멤버 테이블
--DROP 트리거, 시퀀스, 테이블
DROP TABLE TB_CHAT_MBR;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_CHAT_MBR
(
    CHAT_SEQ      NUMBER           NOT NULL, 
    ID            VARCHAR2(20)     NOT NULL, 
    CM_DOC        VARCHAR2(100)    NULL, 
    CM_CHAT_NO    NUMBER           NULL, 
    CONSTRAINT TB_CHAT_MBR_PK PRIMARY KEY (ID, CHAT_SEQ)
);

ALTER TABLE TB_CHAT_MBR
    ADD CONSTRAINT FK_TB_CHAT_MBR_ID_TB_USER_ID FOREIGN KEY (ID)
        REFERENCES TB_USER(ID);
       
ALTER TABLE TB_CHAT_MBR
    ADD CONSTRAINT FK_TB_CHAT_MBR_CHAT_SEQ_TB_CHA FOREIGN KEY (CHAT_SEQ)
        REFERENCES TB_CHAT (CHAT_SEQ);

--오프라인 스터디모임 게시판
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_STUDY_AI_TRG;
DROP SEQUENCE TB_STUDY_SEQ;
DROP TABLE TB_STUDY;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_STUDY
(
    STD_SEQ         NUMBER            NOT NULL, 
    STD_TITLE       VARCHAR2(100)     NOT NULL, 
    STD_CONTENTS    VARCHAR2(1000)    NOT NULL, 
    STD_DT          VARCHAR2(12)      NOT NULL, 
    STD_ID          VARCHAR2(20)      NOT NULL, 
    STD_STAT        VARCHAR2(20)      NOT NULL, 
    STD_SHOW_YN     CHAR(1)           NOT NULL, 
    STD_MBR_NUM     NUMBER            NOT NULL, 
    CONSTRAINT TB_STUDY_PK PRIMARY KEY (STD_SEQ)
);

CREATE SEQUENCE TB_STUDY_SEQ;

CREATE OR REPLACE TRIGGER TB_STUDY_AI_TRG
BEFORE INSERT ON TB_STUDY 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_STUDY_SEQ.NEXTVAL
    INTO :NEW.STD_SEQ
    FROM DUAL;
END;

--오프라인 스터디 참여멤버
--DROP 테이블
DROP TABLE TB_STD_MBR;
--CREATE 테이블
CREATE TABLE TB_STD_MBR
(
    STD_SEQ      NUMBER          NOT NULL, 
    ID           VARCHAR2(20)    NOT NULL 
    CONSTRAINT TB_STD_MBR_PK PRIMARY KEY (ID)
);
ALTER TABLE TB_STD_MBR
    ADD CONSTRAINT FK_TB_STD_MBR_STD_SEQ_TB_STUDY FOREIGN KEY (STD_SEQ)
        REFERENCES TB_STUDY (STD_SEQ);
ALTER TABLE TB_STD_MBR
    ADD CONSTRAINT FK_TB_STD_MBR_ID_TB_USER_ID FOREIGN KEY (ID)
        REFERENCES TB_USER (ID);

ALTER TABLE TB_STD_MBR DROP PRIMARY KEY;
-- 두개의 컬럼을 PRIMARY KEY로
ALTER TABLE TB_STD_MBR ADD PRIMARY KEY(STD_SEQ,ID);


--QnA
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_QNA_AI_TRG;
DROP SEQUENCE TB_QNA_SEQ;
DROP TABLE TB_QNA;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_QNA
(
    Q_SEQ             NUMBER            NOT NULL, 
    Q_GRP_SEQ         NUMBER            NOT NULL, 
    Q_PW              VARCHAR2(20)      NOT NULL, 
    Q_STAT            VARCHAR2(20)      NOT NULL, 
    Q_TITLE           VARCHAR2(1000)    NOT NULL, 
    Q_CONTENTS        VARCHAR2(2000)    NOT NULL, 
    Q_ORI_FILE_NM     VARCHAR2(1000)    NULL, 
    Q_SAVE_FILE_NM    VARCHAR2(1000)    NULL, 
    Q_SAVE_PATH       VARCHAR2(2000)    NULL, 
    ID                VARCHAR2(50)      NOT NULL, 
    Q_INST_DT         DATE              NOT NULL, 
    RE_ID             VARCHAR2(50)      NULL, 
    RE_CONTENTS       VARCHAR2(2000)    NULL, 
    CONSTRAINT TB_QNA_PK PRIMARY KEY (Q_SEQ)
);
ALTER TABLE TB_QNA
    ADD CONSTRAINT FK_TB_QNA_ID_TB_USER_ID FOREIGN KEY (ID)
        REFERENCES TB_USER (ID);

CREATE SEQUENCE TB_QNA_SEQ;

CREATE OR REPLACE TRIGGER TB_QNA_AI_TRG
BEFORE INSERT ON TB_QNA 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_QNA_SEQ.NEXTVAL
    INTO :NEW.Q_SEQ
    FROM DUAL;
END;






