--유저테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_USER_AI_TRG;
DROP SEQUENCE TB_USER_SEQ;
DROP TABLE TB_USER;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_USER
(
    ID_GUBUN    VARCHAR2(20)    NOT NULL, 
    ID_SEQ      NUMBER          NOT NULL, 
    ID          VARCHAR2(20)    NOT NULL, 
    PW          VARCHAR2(20)    NOT NULL, 
    EMAIL       VARCHAR2(50)    NOT NULL, 
    PHONE       VARCHAR2(50)    NOT NULL, 
    TG_NO       VARCHAR2(20)    NULL, 
    TG_YN       CHAR(1)         NOT NULL, 
    USER_YN     CHAR(1)         NOT NULL, 
    AP_RSLT     VARCHAR2(20)    NULL, 
    OUT_RS      VARCHAR2(20)    NULL, 
    DAL_CNT     NUMBER          NULL, 
    CONSTRAINT TB_USER_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE TB_USER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TB_USER_AI_TRG
BEFORE INSERT ON TB_USER 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_USER_SEQ.NEXTVAL
    INTO :NEW.ID_SEQ
    FROM DUAL;
END;


INSERT INTO TB_USER VALUES('USER','kh1','1234','michaelhj@naver.com','01039107929','','N','Y','','',0);
SELECT * FROM TB_USER;
SELECT * FROM TB_USER WHERE ID='kh';
SELECT ID, PW, EMAIL, PHONE FROM TB_USER WHERE ID = 'kh'