--회원테이블 더미데이터 
SELECT * FROM TB_USER;

INSERT INTO TB_USER (ID_GUBUN, ID, PW, EMAIL, PHONE, TG_YN, USER_YN)
VALUES('USER', 'USER01', 'USER01', 'USER01@GMAIL.COM', '010-0000-0001', 'N', 'Y');

INSERT INTO TB_USER (ID_GUBUN, ID, PW, EMAIL, PHONE, TG_YN, USER_YN)
VALUES('USER', 'USER02', 'USER02', 'USER02@GMAIL.COM', '010-0000-0002', 'N', 'Y');

INSERT INTO TB_USER (ID_SEQ, ID_GUBUN, ID, PW, EMAIL, PHONE, TG_YN, USER_YN)
VALUES(TB_USER_SEQ.NEXTVAL, 'ADMIN', 'ADMIN01', 'ADMIN01', 'ADMIN01@GMAIL.COM', '010-0000-0001', 'N', 'Y');

--qna 테이블
SELECT * FROM TB_QNA;

INSERT INTO TB_QNA (Q_GRP_SEQ, Q_PW, Q_STAT, Q_TITLE, Q_CONTENTS, ID, Q_INST_DT)
VALUES(1, 'USER01', 'R', 'TITLE01', 'CONTENTS01', 'USER01', SYSDATE);
INSERT INTO TB_QNA (Q_GRP_SEQ, Q_PW, Q_STAT, Q_TITLE, Q_CONTENTS, ID, Q_INST_DT)
VALUES(2, 'USER02', 'R', 'TITLE02', 'CONTENTS02', 'USER02', SYSDATE);

SELECT RM, Q_SEQ, Q_PW, Q_STAT, Q_TITLE, ID, Q_INST_DT
FROM (
SELECT ROWNUM AS RM, Q_SEQ, Q_PW, Q_STAT, Q_TITLE, ID, TO_CHAR(Q_INST_DT, 'YYYY-MM-DD') AS Q_INST_DT
FROM (
SELECT Q_SEQ, Q_PW, Q_STAT, Q_TITLE, ID, Q_INST_DT 
FROM TB_QNA
ORDER BY Q_INST_DT DESC
))
WHERE RM BETWEEN 1 AND 6; 
		
SELECT count(*) as cnt 
FROM TB_QNA;

ALTER TABLE TB_QNA RENAME COLUMN Q_IMG_URL TO Q_ORI_FILE_NM;
ALTER TABLE TB_QNA ADD(Q_SAVE_FILE_NM VARCHAR2(1000));
ALTER TABLE TB_QNA ADD(Q_SAVE_PATH VARCHAR2(2000));
ALTER TABLE TB_QNA DROP COLUMN RE_DT;

SELECT ts.STD_SEQ, STD_TITLE, STD_DT, STD_ID, STD_MBR_NUM, ID
FROM TB_STUDY ts, TB_STD_MBR tsm
WHERE ts.STD_SEQ = tsm.STD_SEQ;


GROUP BY ts.STD_SEQ, STD_TITLE, STD_DT, STD_ID, STD_MBR_NUM;




SELECT ts.STD_SEQ, STD_TITLE, STD_DT, STD_ID, STD_MBR_NUM, count(*) AS MBR_CNT
FROM TB_STUDY ts, TB_STD_MBR tsm
WHERE ts.STD_SEQ = tsm.STD_SEQ
GROUP BY ts.STD_SEQ, STD_TITLE, STD_DT, STD_ID, STD_MBR_NUM;

SELECT * FROM TB_STD_MBR;

