--초기화 해야해서.... drop먼저 아래에서 위로 한번, 위에서 아래로 한번 하시고  순서대로 추가해주세요
-- 변경사항 -- 등록을 하는 날짜(qna)를 제외하고 날짜를 다루는 컬럼의 값을 VARCHAR2로 변환했음.
-- 이때 DATE를 YYYYMMDDHHmm으로 처리해서 12자리로 통일.

--채팅테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_CHAT_AI_TRG;
DROP SEQUENCE TB_CHAT_SEQ;
DROP TABLE TB_CHAT;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_CHAT
(
    CHAT_SEQ         NUMBER          NOT NULL, 
    CHAT_TITLE       VARCHAR2(20)    NOT NULL, 
    CHAT_MGR         VARCHAR2(20)    NOT NULL, 
    CHAT_ST_DT       VARCHAR2(12)    NOT NULL, 
    CHAT_END_DT      VARCHAR2(12)    NOT NULL, 
    CHAT_FINAL_DT    VARCHAR2(12)    NOT NULL, 
    CHAT_STAT        VARCHAR2(20)    NOT NULL, 
    CHAT_TG_YN       CHAR(1)         NOT NULL, 
    CONSTRAINT TB_CHAT_PK PRIMARY KEY (CHAT_SEQ)
);

CREATE SEQUENCE TB_CHAT_SEQ;

CREATE OR REPLACE TRIGGER TB_CHAT_AI_TRG
BEFORE INSERT ON TB_CHAT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_CHAT_SEQ.NEXTVAL
    INTO :NEW.CHAT_SEQ
    FROM DUAL;
END;

--유저테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_USER_AI_TRG;
DROP SEQUENCE TB_USER_SEQ;
DROP TABLE TB_USER;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_USER
(
    ID_GUBUN    VARCHAR2(20)    NOT NULL, 
    ID_SEQ      NUMBER          NOT NULL, 
    ID          VARCHAR2(20)    NOT NULL, 
    PW          VARCHAR2(20)    NOT NULL, 
    EMAIL       VARCHAR2(50)    NOT NULL, 
    PHONE       VARCHAR2(50)    NOT NULL, 
    TG_NO       VARCHAR2(20)    NULL, 
    TG_YN       CHAR(1)         NOT NULL, 
    USER_YN     CHAR(1)         NOT NULL, 
    AP_RSLT     VARCHAR2(20)    NULL, 
    OUT_RS      VARCHAR2(20)    NULL, 
    DAL_CNT     NUMBER          NULL, 
    CONSTRAINT TB_USER_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE TB_USER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TB_USER_AI_TRG
BEFORE INSERT ON TB_USER 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_USER_SEQ.NEXTVAL
    INTO :NEW.ID_SEQ
    FROM DUAL;
END;

--채팅 참여 멤버 테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_CHAT_MBR_AI_TRG;
DROP SEQUENCE TB_CHAT_MBR_SEQ;
DROP TABLE TB_CHAT_MBR;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_CHAT_MBR
(
    CHAT_SEQ      NUMBER           NOT NULL, 
    ID            VARCHAR2(20)     NOT NULL, 
    CM_DOC        VARCHAR2(100)    NULL, 
    CM_CHAT_NO    NUMBER           NULL, 
    CONSTRAINT TB_CHAT_MBR_PK PRIMARY KEY (ID)
);
ALTER TABLE TB_CHAT_MBR
    ADD CONSTRAINT FK_TB_CHAT_MBR_ID_TB_USER_ID FOREIGN KEY (ID)
        REFERENCES TB_USER (ID);
ALTER TABLE TB_CHAT_MBR
    ADD CONSTRAINT FK_TB_CHAT_MBR_CHAT_SEQ_TB_CHA FOREIGN KEY (CHAT_SEQ)
        REFERENCES TB_CHAT (CHAT_SEQ);

CREATE SEQUENCE TB_CHAT_MBR_SEQ;

CREATE OR REPLACE TRIGGER TB_CHAT_MBR_AI_TRG
BEFORE INSERT ON TB_CHAT_MBR 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_CHAT_MBR_SEQ.NEXTVAL
    INTO :NEW.CHAT_SEQ
    FROM DUAL;
END;

--면접 피드백 테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_FEED_AI_TRG;
DROP SEQUENCE TB_FEED_SEQ;
DROP TABLE TB_FEED;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_FEED
(
    FD_SEQ         NUMBER            NOT NULL, 
    CHAT_SEQ       NUMBER            NOT NULL, 
    FD_TITLE       VARCHAR2(100)     NOT NULL, 
    FD_CONTENTS    VARCHAR2(1000)    NOT NULL, 
    ID             VARCHAR2(20)      NOT NULL, 
    FD_USER        VARCHAR2(20)      NOT NULL, 
    FD_DT          VARCHAR2(12)      NOT NULL, 
    CONSTRAINT TB_FEED_PK PRIMARY KEY (FD_SEQ)
);
ALTER TABLE TB_FEED
    ADD CONSTRAINT FK_TB_FEED_CHAT_SEQ_TB_CHAT_CH FOREIGN KEY (CHAT_SEQ)
        REFERENCES TB_CHAT (CHAT_SEQ);
ALTER TABLE TB_FEED
    ADD CONSTRAINT FK_TB_FEED_ID_TB_CHAT_MBR_ID FOREIGN KEY (ID)
        REFERENCES TB_CHAT_MBR (ID);

CREATE SEQUENCE TB_FEED_SEQ;

CREATE OR REPLACE TRIGGER TB_FEED_AI_TRG
BEFORE INSERT ON TB_FEED 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_FEED_SEQ.NEXTVAL
    INTO :NEW.FD_SEQ
    FROM DUAL;
END;



--신고테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_USR_REPORT_AI_TRG;
DROP SEQUENCE TB_USR_REPORT_SEQ;
DROP TABLE TB_USR_REPORT;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_USR_REPORT
(
    RPT_SEQ         NUMBER          NOT NULL, 
    RPT_CONTENTS    VARCHAR2(20)    NOT NULL, 
    ID              VARCHAR2(20)    NOT NULL, 
    RPTER_ID        VARCHAR2(20)    NOT NULL, 
    CONSTRAINT TB_USR_REPORT_PK PRIMARY KEY (RPT_SEQ)
);
ALTER TABLE TB_USR_REPORT
    ADD CONSTRAINT FK_TB_USR_REPORT_ID_TB_USER_ID FOREIGN KEY (ID)
        REFERENCES TB_USER (ID);

CREATE SEQUENCE TB_USR_REPORT_SEQ;

CREATE OR REPLACE TRIGGER TB_USR_REPORT_AI_TRG
BEFORE INSERT ON TB_USR_REPORT 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_USR_REPORT_SEQ.NEXTVAL
    INTO :NEW.RPT_SEQ
    FROM DUAL;
END;

--오프라인 스터디모임 게시판
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_STUDY_AI_TRG;
DROP SEQUENCE TB_STUDY_SEQ;
DROP TABLE TB_STUDY;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_STUDY
(
    STD_SEQ         NUMBER            NOT NULL, 
    STD_TITLE       VARCHAR2(100)     NOT NULL, 
    STD_CONTENTS    VARCHAR2(1000)    NOT NULL, 
    STD_DT          VARCHAR2(12)      NOT NULL, 
    STD_ID          VARCHAR2(20)      NOT NULL, 
    STD_STAT        VARCHAR2(20)      NOT NULL, 
    STD_SHOW_YN     CHAR(1)           NOT NULL, 
    STD_MBR_NUM     NUMBER            NOT NULL, 
    CONSTRAINT TB_STUDY_PK PRIMARY KEY (STD_SEQ)
);

CREATE SEQUENCE TB_STUDY_SEQ;

CREATE OR REPLACE TRIGGER TB_STUDY_AI_TRG
BEFORE INSERT ON TB_STUDY 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_STUDY_SEQ.NEXTVAL
    INTO :NEW.STD_SEQ
    FROM DUAL;
END;

--오프라인 스터디 참여멤버
--DROP 테이블
DROP TABLE TB_STD_MBR;
--CREATE 테이블
CREATE TABLE TB_STD_MBR
(
    STD_SEQ      NUMBER          NOT NULL, 
    ID           VARCHAR2(20)    NOT NULL, 
    STMB_LAT     NUMBER          NOT NULL, 
    STMB_LONG    NUMBER          NOT NULL, 
    CONSTRAINT TB_STD_MBR_PK PRIMARY KEY (ID)
);
ALTER TABLE TB_STD_MBR
    ADD CONSTRAINT FK_TB_STD_MBR_STD_SEQ_TB_STUDY FOREIGN KEY (STD_SEQ)
        REFERENCES TB_STUDY (STD_SEQ);
ALTER TABLE TB_STD_MBR
    ADD CONSTRAINT FK_TB_STD_MBR_ID_TB_USER_ID FOREIGN KEY (ID)
        REFERENCES TB_USER (ID);
       
--QnA
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_QNA_AI_TRG;
DROP SEQUENCE TB_QNA_SEQ;
DROP TABLE TB_QNA;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_QNA
(
    Q_SEQ          NUMBER            NOT NULL, 
    Q_GRP_SEQ      NUMBER      		 NOT NULL, 
    Q_PW           VARCHAR2(20)      NOT NULL, 
    Q_STAT         VARCHAR2(20)      NOT NULL, 
    Q_TITLE        VARCHAR2(1000)    NOT NULL, 
    Q_CONTENTS     VARCHAR2(2000)    NOT NULL, 
    Q_IMG_URL      VARCHAR2(1000)    NULL, 
    ID             VARCHAR2(20)      NOT NULL, 
    Q_INST_DT      DATE              NOT NULL, 
    RE_ID          VARCHAR2(20)      NULL, 
    RE_CONTENTS    VARCHAR2(2000)    NULL, 
    RE_DT          DATE              NULL, 
    CONSTRAINT TB_QNA_PK PRIMARY KEY (Q_SEQ)
);
ALTER TABLE TB_QNA
    ADD CONSTRAINT FK_TB_QNA_ID_TB_USER_ID FOREIGN KEY (ID)
        REFERENCES TB_USER (ID);

CREATE SEQUENCE TB_QNA_SEQ;

CREATE OR REPLACE TRIGGER TB_QNA_AI_TRG
BEFORE INSERT ON TB_QNA 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_QNA_SEQ.NEXTVAL
    INTO :NEW.Q_SEQ
    FROM DUAL;
END;

--채용정보 테이블
--DROP 트리거, 시퀀스, 테이블
DROP TRIGGER TB_EM_INFO_AI_TRG;
DROP SEQUENCE TB_EM_INFO_SEQ;
DROP TABLE TB_EM_INFO;
--CREATE 테이블, 시퀀스, 트리거
CREATE TABLE TB_EM_INFO
(
    INFO_SEQ         NUMBER            NOT NULL, 
    INFO_TITLE       VARCHAR2(100)     NOT NULL, 
    INFO_CONTENTS    CLOB              NOT NULL, 
    INFO_IMG_URL     VARCHAR2(1000)    NULL, 
    INFO_INST_DT     VARCHAR2(12)      NOT NULL, 
    INFO_END_DT      VARCHAR2(12)      NOT NULL, 
    INFO_SITE_URL    VARCHAR2(1000)    NOT NULL, 
    CONSTRAINT TB_EM_INFO_PK PRIMARY KEY (INFO_SEQ)
);

CREATE SEQUENCE TB_EM_INFO_SEQ;

CREATE OR REPLACE TRIGGER TB_EM_INFO_AI_TRG
BEFORE INSERT ON TB_EM_INFO 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT TB_EM_INFO_SEQ.NEXTVAL
    INTO :NEW.INFO_SEQ
    FROM DUAL;
END;





